### ISSUE TITLE
Login Page Render Issue

### ISSUE THREAD

**Issue by wrandall22** [CruGlobal/scale-of-belief-web#14]
On Logout and Login, there is a stacktrace in the console that comes up. The user doesn't see anything (unless they are looking at the console logs).

````
uncaught at handleAuth Invariant Violation: loginPage.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
    at invariant (http://content-scoring-local.cru.org:3001/static/js/bundle.js:28851:15)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://content-scoring-local.cru.org:3001/static/js/bundle.js:92530:111)
    at ReactCompositeComponentWrapper.performInitialMount (http://content-scoring-local.cru.org:3001/static/js/bundle.js:92061:30)
    at ReactCompositeComponentWrapper.mountComponent (http://content-scoring-local.cru.org:3001/static/js/bundle.js:91957:21)
    at Object.mountComponent (http://content-scoring-local.cru.org:3001/static/js/bundle.js:98647:35)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://content-scoring-local.cru.org:3001/static/js/bundle.js:92464:40)
    at ReactCompositeComponentWrapper._performComponentUpdate (http://content-scoring-local.cru.org:3001/static/js/bundle.js:92423:10)
    at ReactCompositeComponentWrapper.updateComponent (http://content-scoring-local.cru.org:3001/static/js/bundle.js:92344:12)
    at ReactCompositeComponentWrapper.receiveComponent (http://content-scoring-local.cru.org:3001/static/js/bundle.js:92246:10)
    at Object.receiveComponent (http://content-scoring-local.cru.org:3001/static/js/bundle.js:98726:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://content-scoring-local.cru.org:3001/static/js/bundle.js:92453:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (http://content-scoring-local.cru.org:3001/static/js/bundle.js:92423:10)
    at ReactCompositeComponentWrapper.updateComponent (http://content-scoring-local.cru.org:3001/static/js/bundle.js:92344:12)
    at ReactCompositeComponentWrapper.receiveComponent (http://content-scoring-local.cru.org:3001/static/js/bundle.js:92246:10)
    at Object.receiveComponent (http://content-scoring-local.cru.org:3001/static/js/bundle.js:98726:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://content-scoring-local.cru.org:3001/static/js/bundle.js:92453:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (http://content-scoring-local.cru.org:3001/static/js/bundle.js:92423:10)
    at ReactCompositeComponentWrapper.updateComponent (http://content-scoring-local.cru.org:3001/static/js/bundle.js:92344:12)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (http://content-scoring-local.cru.org:3001/static/js/bundle.js:92260:12)
    at Object.performUpdateIfNecessary (http://content-scoring-local.cru.org:3001/static/js/bundle.js:98758:22)
    at runBatchedUpdates (http://content-scoring-local.cru.org:3001/static/js/bundle.js:99515:21)
    at ReactReconcileTransaction.perform (http://content-scoring-local.cru.org:3001/static/js/bundle.js:101494:20)
    at ReactUpdatesFlushTransaction.perform (http://content-scoring-local.cru.org:3001/static/js/bundle.js:101494:20)
    at ReactUpdatesFlushTransaction.perform (http://content-scoring-local.cru.org:3001/static/js/bundle.js:99454:32)
    at Object.flushBatchedUpdates (http://content-scoring-local.cru.org:3001/static/js/bundle.js:99537:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (http://content-scoring-local.cru.org:3001/static/js/bundle.js:101560:25)
    at ReactDefaultBatchingStrategyTransaction.perform (http://content-scoring-local.cru.org:3001/static/js/bundle.js:101507:16)
    at Object.batchedUpdates (http://content-scoring-local.cru.org:3001/static/js/bundle.js:96213:26)
    at Object.enqueueUpdate (http://content-scoring-local.cru.org:3001/static/js/bundle.js:99565:22)
    at enqueueUpdate (http://content-scoring-local.cru.org:3001/static/js/bundle.js:99146:16)
    at Object.enqueueSetState (http://content-scoring-local.cru.org:3001/static/js/bundle.js:99340:5)
    at Router../node_modules/react/lib/ReactBaseClasses.js.ReactComponent.setState (http://content-scoring-local.cru.org:3001/static/js/bundle.js:119019:16)
    at http://content-scoring-local.cru.org:3001/static/js/bundle.js:115698:14
    at listener (http://content-scoring-local.cru.org:3001/static/js/bundle.js:30535:24)
    at http://content-scoring-local.cru.org:3001/static/js/bundle.js:30554:23
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (http://content-scoring-local.cru.org:3001/static/js/bundle.js:30553:15)
    at setState (http://content-scoring-local.cru.org:3001/static/js/bundle.js:30066:23)
    at http://content-scoring-local.cru.org:3001/static/js/bundle.js:30174:9
    at Object.confirmTransitionTo (http://content-scoring-local.cru.org:3001/static/js/bundle.js:30525:7)
    at Object.push (http://content-scoring-local.cru.org:3001/static/js/bundle.js:30154:23)
    at http://content-scoring-local.cru.org:3001/static/js/bundle.js:114393:25
    at http://content-scoring-local.cru.org:3001/static/js/bundle.js:129907:22
    at dispatch (http://content-scoring-local.cru.org:3001/static/js/bundle.js:131510:18)
    at http://content-scoring-local.cru.org:3001/static/js/bundle.js:131400:12
    at http://content-scoring-local.cru.org:3001/static/js/bundle.js:130424:52
    at exec (http://content-scoring-local.cru.org:3001/static/js/bundle.js:131063:5)
    at flush (http://content-scoring-local.cru.org:3001/static/js/bundle.js:131104:5)
    at asap (http://content-scoring-local.cru.org:3001/static/js/bundle.js:131077:5)
    at runPutEffect (http://content-scoring-local.cru.org:3001/static/js/bundle.js:130421:69)
````

**Comment by wrandall22** [comment]
Another place to see the stack trace is here: http://content-scoring-local.cru.org:3001/#/login
